/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ghost;

import org.junit.jupiter.api.Test;

import processing.core.PApplet;

import static org.junit.jupiter.api.Assertions.*;

class AppTest{ 
    @Test 
    public void simpleTest() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest);
    }

    @Test
    public void testGetRunner(){
        App app = new App();
        assertNull(app.getRunner());
    }

    @Test
    public void testSetup(){
        App app = new App();
        PApplet.runSketch(new String[] {"App"}, app);
        app.setup();
        
    }

    @Test
    public void testSetting(){
        App app = new App();
        PApplet.runSketch(new String[] {"App"}, app);
        app.settings();
    }


}
